### ISSUE TITLE
A weird verification result

### ISSUE THREAD

**Issue by zhangyedi** [mlech26l/qnn_robustness_benchmarks#3]
Hi, @mlech26l

I change your encoding.arg_not_max function into another property as follows,
```
def assert_not_argmax(self, max_index):
    lte_func = self.btor.Slte if self._last_layer_signed else self.btor.Ulte
    if max_index == 9:
        tmp = 0
        for i in range(9):
            tmp = self.btor.Add(tmp, self.output_vars[i])
        disjunction = lte_func(9 * self.output_vars[int(max_index)], tmp_smt)  # sat
        self.btor.Assert(disjunction)
    else:
        exit(0)
```

, which means the 9*output[9]<=output[0]+...+output[8]. In other words, if the property holds, then we must find an adversarial example for the input instance (we only process the input instance 9 which is correctly predicted). When I run the instance 151(whose prediction is image-9) in MNIST with eps=1, i.e. `--sample_id 151 --eps 1 --dataset mnist,` the verification result looks weird: `mnist test sample 151 is NOT robust! Predicted original class is 9, vs attacked image is predicted as 9`. It seems that the model returned from smt-formula is not a real solution for this verification problem of the network (input_bits=8, quantization_bits=6), since the model satisfying this property must be predicted as another class with this QNN. Also I print the output of the last layer for the solution returned from boolector as follows: `[-2.     -2.     -2.     -0.875  -2.     -2.     -2.     -2.      1.1875  1.5625 -2.     -2.     -2.     -2.     -2.     -2.     -2.     -2. -2.     -2.     -2.     -2.     -2.     -2.     -2.     -2.     -2. -2.     -2.     -2.     -2.     -2.    ]` In fact, the property `9*output[9]<=output[0]+...+output[8]` does not hold for this solution. Is it possible that there is a problem with the implementation of smt-bv encoding, or I miss something?

Yedi

**Comment by mlech26l** [comment]
Hi @zhangyedi 

Here, it seems that the semantics of the BV encoding differs from the TF semantics (the text ```attacked image is predicted as X``` is generated from the prediction of the TF semantics, while the counterexample is generated with the BV semantics).

For me, it looks like the issue is caused by the summation of the ```self.output_vars```. As the BV variables are only 6 bits, there is a high chance of an over/underflow happening here when they are summed up.
The TF semantics does not actually use integers but floats that are rounded, thus there cannot be an overflow in the TF semantics.

So in essence, I think that the counterexample generated by the BV encoding exploits some over/underflow that is not present in the TF semantics. 
One thing to try is to extend the bit-width of the ```output_vars``` and see if this resolves the problem (though high-bit operations can make the SMT solver very slow)

**Comment by zhangyedi** [comment]
Oh, yes! After I extend the bit-width, the verification result becomes normal. Thanks very much for your immediate reply!!! :)

**Comment by mlech26l** [comment]
Great. You are welcome
